export  default ({
    external:{_}
})=>()=>({mountNodes,
    childNodes:{present,future,...childNodes}
})=>(spaceTime)=>(filter)=>mountNodes({
    scope:{},
    nodes:_(childNodes).reduce(
        (nodes,{
            me:childNode,
            dollar$obj_func:{buildtime$getDollar:{dollar$getObj:{
                buildtime$getDollar:childBuildtime$getDollar
            }}}
        },firstName)=>(
            filter(childBuildtime$getDollar())?{...nodes,
                [firstName]:childNode
            }:nodes
        ),
        {}
    ),
    get:({get$getFunc})=>get$getFunc(spiceTime)
})