export default ({
    external:{_}
})=>({
    path:pPath,
    me:pNode,
    constructor:{instance$get:node$get}
})=>(filter,nodeSpecs)=>_.reduce(
    nodeSpecs,
    (nodes,{
        me:nodeSpec,
        nameHandle:{firstName,fullName}
    })=>(
        filter(nodeSpec)?{...nodes,
            [firstName]:node$get({pNode,nodeSpec,
                path:pPath+'/'+fullName
            })
        }:nodes
    ),
    {}
)
